# Review

What is an array/list?

Answer:  An array (or list) is a data structure that stores multiple values in an ordered sequence, allowing efficient indexing, retrieval, and manipulation.


Define an array best_test_array as these numbers:  5,3,9,1,4,9,11,22,54,71,2.   

In [1]:
best_test_array = [5, 3, 9, 1, 4, 9, 11, 22, 54, 71, 2]
print(best_test_array)

[5, 3, 9, 1, 4, 9, 11, 22, 54, 71, 2]


Use indexing to pull out the number 11.

In [2]:
eleven = best_test_array[6]
print(eleven)

11


Use slicing to pull out the number 54, 71, 2.

In [3]:
slice1 = best_test_array[8:11]
print(slice1)

[54, 71, 2]


Use slicing to pull out the numbers 9,1,4,9.

In [4]:
slice2 = best_test_array[2:6]
print(slice2)

[9, 1, 4, 9]


# Array Indexing

Example 1: Import the numpy module as np.

In [5]:
import numpy as np

Example 2a: Define this array [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]] using numpy and name it test_array.

In [6]:
test_array = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30]
])
print(test_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


Example 2b: Use indexing to return 1.

In [7]:
value_1 = test_array[0, 0]
print(value_1)

1


Task 1: Use indexing to return 11.

In [8]:
value_11 = test_array[2, 0]
print(value_11)

11


Task 1a: Use indexing to return 23.

In [9]:
value_23 = test_array[4, 2]
print(value_23)

23


Task 1b: Use indexing to return 9.

In [10]:
value_9 = test_array[1, 3]
print(value_9)

9


## **Using Numpy** -- Understanding Shape and Dimension of Arrays

Import numpy module as np

In [2]:
import numpy as np

Example 1a: Create a scalar array with a value of 255 using the numpy method array, and name it scale_by.

In [6]:
scale_by = np.array(255)
print(scale_by)

255


Task 1a: Create a scalar array with a value of 50 using the numpy method array and name it scaling.

In [7]:
scaling = np.array(50)
print(scaling)

50


Example 1b:  Determine the dimensions of the array scale_by using the ndim method of numpy.

In [8]:
scale_by_dim = scale_by.ndim
print(scale_by_dim)

0


Task 1b: Determine the dimensions of the array scaling using the ndim method of numpy.

In [9]:
scaling_dim = scaling.ndim
print(scaling_dim)

0


Eample 2a: Define the following arrays: a = [1, 1, 1, 1] the using the numpy array the  then use the numpy shape method to determine the shape of this array.


In [10]:
a = np.array([1, 1, 1, 1])
a_shape = a.shape
print(a_shape)

(4,)


Example 2b: Use the ndim method of numpy to determine the dimensions of a.

In [11]:
a_dim = a.ndim

In [12]:
print(a_dim)

1


Task 2a: Define the following arrays: b = [4,2,5,3,6,5] the using the numpy array the then use the numpy shape method to determine the shape of this array.

In [13]:
b = np.array([4, 2, 5, 3, 6, 5])
b_shape = b.shape
print(b_shape)

(6,)


Task 2b: Use the ndim method of numpy to determine the dimensions of b.

In [14]:
b_dim = b.ndim
print(b_dim)

1


# Slicing Review:

Example: Define a list t, slice to get the last three numbers in the list and call them z. Print z.

In [15]:
t = [10, 20, 30, 40, 50, 60]
z = t[-3:]  # Slicing last three numbers
print(z)  # Output: [40, 50, 60]


[40, 50, 60]


Task 2c: Use slicing to assign the last three values in b to c.

In [16]:
b = np.array([4, 2, 5, 3, 6, 5])
c = b[-3:]
print(c)

[3 6 5]


Task 2d: Determine the dimensions of c.

In [17]:
c_dim = c.ndim
print(c_dim)

1


Task 2e: Determine the shape of c.

In [18]:
c_shape = c.shape
print(c_shape)

(3,)


Task 3a: Use a for loop to print all of the values in c.

In [19]:
for value in c:
    print(value)

3
6
5


Example 4a: Define the following array: b = [[1,1,1,1],[1,1,1,1]] and use the numpy method to determine the shape of this array.

In [4]:
import numpy as np
b = np.array([[1,1,1,1],[1,1,1,1]])
print(b.shape)


(2, 4)


Task 4a: Use the numpy method ndim to determine the number of dimensions.

In [20]:
print(c.ndim)

1


Task 5a: Define the following array: c = [[1,1,1,1],[1,1,1,1],[1,1,1,1]] and use the numpy method to determine the shape of this array.

In [21]:
c = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])
print(c.shape) 

(3, 4)


Task 5b: Use the numpy method ndim to determine the number of dimensions.

In [22]:
print(c.ndim)

2


Example 6a: Create an array of shape (5, 3), and query its shape to confirm.

In [23]:
array_6a = np.zeros((5, 3))

In [24]:
print(array_6a.shape)

(5, 3)


Task 6a: Create an array of shape (6, 4), name it f, and query its shape to confirm.

In [25]:
f = np.zeros((6, 4))
print(f.shape)

(6, 4)


Task 6b: Use the numpy method ndim to determine the number of dimensions.

In [26]:
print(f.ndim)

2


Task 7a: Create an array of shape (1, 10) and query shape to confirm.

In [27]:
array_7a = np.zeros((1, 10))

In [28]:
print(array_7a.shape) 

(1, 10)


Task 7b: Use the numpy method ndim to determine the number of dimensions.

In [29]:
print(array_7a.ndim)

2


## **Accessing array contents**

Review 1: Remember to access items in a list, you use indexing.  For example, to access "this" in the list: t = ['we', 'this', 'the', 'they', 'them']

In [31]:
t = ['we', 'this', 'the', 'they', 'them']
print(t[1])

this


Example 2a: Define this array [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]] using numpy and name it test_array.

In [ ]:
test_array = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30]
])


Task 2b: Determine the shape of test_array.

In [32]:
print(test_array.shape)

(6, 5)


Task 2c: Determine the dimensions of test_array.

In [33]:
print(test_array.ndim)

2


Example 2d: Use indexing to print out 14.

In [34]:
print(test_array[2, 3])

14


Task 2d: Use indexing to print out 22 from test_array.

In [35]:
print(test_array[4, 1])

22


Example 2e:  Use indexing to print out [21, 22, 23 ,24, 25] from test_array.

In [36]:
print(test_array[4])

[21 22 23 24 25]


Task 2e: Use indexing to print out [11,12,13,14,15]

In [37]:
print(test_array[2])

[11 12 13 14 15]


Task 1a: Define this 3 dimensional array, display it for you to see, and confirm its shape is (6,4) and its dimensions are 2.

g = np.array([[1,2,3,4],[6,7,8,9],[11,12,13,14],[16,17,18,19],[21,22,23,24],[26,27,28,29]])

In [38]:
g = np.array([
    [1, 2, 3, 4],
    [6, 7, 8, 9],
    [11, 12, 13, 14],
    [16, 17, 18, 19],
    [21, 22, 23, 24],
    [26, 27, 28, 29]
])


In [39]:
print(g.shape)

(6, 4)


In [41]:
print(g.ndim)

2


Task 1b: Access [[1,2,3,4],[6,7,8,9]]

In [42]:
print(g[:2])

[[1 2 3 4]
 [6 7 8 9]]


Task 1c: Access [[ 11, 12, 13, 14],
       [16, 17, 18, 19]]

In [43]:
print(g[2:4])

[[11 12 13 14]
 [16 17 18 19]]


Task 1d: Access[1,2,3,4]

In [44]:
print(g[0])

[1 2 3 4]


Task 1e: Access 1

In [45]:
print(g[0, 0])

1


Task 1f: Access the middle two columns.

In [46]:
print(g[:, 1:3])

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]
 [27 28]]


Task 1g: Access 9.

In [47]:
print(g[1, 3])

9


Task 1h: Access 18.

In [48]:
print(g[3, 2])

18
