In [1]:
import numpy as np
x = np.array([3,1,4,1])
x.ndim

1

## **Using Numpy** -- Understanding Shape and Dimension of Arrays

Import numpy module as np

In [2]:
import numpy as np

Example 1a: Create a scalar array with a value of 255 using the numpy method array, and name it scale_by.

In [3]:
scale_by = np.array(255)
scale_by

array(255)

Task 1a: Create a scalar array with a value of 50 using the numpy method array and name it scaling.

In [4]:
scaling = np.array(50)
scaling

array(50)

Example 1b:  Determine the dimensions of the array scale_by using the ndim method of numpy.

In [5]:
scale_by.ndim

0

Task 1b: Determine the dimensions of the array scaling using the ndim method of numpy.

0

Eample 2a: Define the following arrays: a = [1, 1, 1, 1] the using the numpy array the  then use the numpy shape method to determine the shape of this array.


In [ ]:
a=np.array([1,1,1,1])
a.shape


(4,)

Example 2b: Use the ndim method of numpy to determine the dimensions of a.

In [ ]:
a.ndim

1

In [ ]:
np.ndim(a)

1

Task 2a: Define the following arrays: b = [4,2,5,3,6,5] the using the numpy array the then use the numpy shape method to determine the shape of this array.

(6,)

Task 2b: Use the ndim method of numpy to determine the dimensions of b.

1

# Slicing Review:

Example: Define a list t, slice to get the last three numbers in the list and call them z. Print z.

In [ ]:
t = [1,2,3,4,5,6,7,8,9]
z= t[6:9]
z

[7, 8, 9]

Task 2c: Use slicing to assign the last three values in b to c.

array([3, 6, 5])

Task 2d: Determine the dimensions of c.

1

Task 2e: Determine the shape of c.

(3,)

Task 3a: Use a for loop to print all of the values in c.

3
6
5


Example 4a: Define the following array: b = [[1,1,1,1],[1,1,1,1]] and use the numpy method to determine the shape of this array.

In [ ]:
b = np.array([[1,1,1,1],
              [1,1,1,1]])
np.shape(b)

(2, 4)

Task 4a: Use the numpy method ndim to determine the number of dimensions.

2

Task 5a: Define the following array: c = [[1,1,1,1],[1,1,1,1],[1,1,1,1]] and use the numpy method to determine the shape of this array.

Task 5b: Use the numpy method ndim to determine the number of dimensions.

2

Example 6a: Create an array of shape (5, 3), and query its shape to confirm.

In [ ]:
fivethree = np.array([[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1]])
fivethree

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.shape(fivethree)

(5, 3)

Task 6a: Create an array of shape (6, 4), name it f, and query its shape to confirm.

(6, 4)

Task 6b: Use the numpy method ndim to determine the number of dimensions.

2

Task 7a: Create an array of shape (1, 10) and query shape to confirm.

(10,)

Task 7b: Use the numpy method ndim to determine the number of dimensions.

1

Example 8a: Create an array with the shape(2,3,4) and query to confirm shape and dimension.



In [ ]:
f = np.array([[[1,1,1,1],
               [1,1,1,1],
               [1,1,1,1]],

              [[1,1,1,1],
               [1,1,1,1],
               [1,1,1,1]]])
np.shape(f)

(2, 3, 4)

In [ ]:
np.ndim(f)

3

Task 8b: Create an array with the dimensions (3, 4, 5), name it three_four_five and query it to confirm its shape, and dimensions.

(3, 4, 5)

## **Accessing array contents**

Review 1: Remember to access items in a list, you use indexing.  For example, to access "this" in the list: t = ['we', 'this', 'the', 'they', 'them']

In [ ]:
t = ['we', 'this', 'the', 'they', 'them']
t[1]

'this'

Example 2a: Define this array [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]] using numpy and name it test_array.

In [ ]:
test_array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
test_array
#np.shape(test_array)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Task 2b: Determine the shape of test_array.

(6, 5)

Task 2c: Determine the dimensions of test_array.

2

Example 2d: Use indexing to print out 14.

In [ ]:
test_array[2][3]

14

Task 2d: Use indexing to print out 22 from test_array.

22

Example 2e:  Use indexing to print out [21, 22, 23 ,24, 25] from test_array.

In [ ]:
test_array[4]

[21, 22, 23, 24, 25]

Task 2e: Use indexing to print out [11,12,13,14,15]

array([11, 12, 13, 14, 15])

Task 1a: Define this 3 dimensional array, display it for you to see, and confirm its shape is (3,2,4) and its dimensions are 3.

g = np.array[[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]]

(3, 2, 4)

3

Task 1b: Access [[1,2,3,4],[5,6,7,8]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Task 1c: Access [[ 9, 10, 11, 12],
       [13, 14, 15, 16]]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Task 1d: Access[1,2,3,4]

array([1, 2, 3, 4])

Task 1e: Access 1

1